package lagern.LagerPackage;

/**
* lagern/LagerPackage/EAlreadyExistsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Mittwoch, 3. April 2013 16:15 Uhr MESZ
*/

public final class EAlreadyExistsHolder implements org.omg.CORBA.portable.Streamable
{
  public lagern.LagerPackage.EAlreadyExists value = null;

  public EAlreadyExistsHolder ()
  {
  }

  public EAlreadyExistsHolder (lagern.LagerPackage.EAlreadyExists initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.LagerPackage.EAlreadyExistsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.LagerPackage.EAlreadyExistsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.LagerPackage.EAlreadyExistsHelper.type ();
  }

}
