package lagern.LagerPackage;


/**
* lagern/LagerPackage/ENotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Mittwoch, 3. April 2013 16:15 Uhr MESZ
*/

public final class ENotFound extends org.omg.CORBA.UserException
{
  public String s = null;

  public ENotFound ()
  {
    super(ENotFoundHelper.id());
  } // ctor

  public ENotFound (String _s)
  {
    super(ENotFoundHelper.id());
    s = _s;
  } // ctor


  public ENotFound (String $reason, String _s)
  {
    super(ENotFoundHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class ENotFound
