package lagern.LagerPackage;

/**
* lagern/LagerPackage/ENotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Mittwoch, 3. April 2013 16:15 Uhr MESZ
*/

public final class ENotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public lagern.LagerPackage.ENotFound value = null;

  public ENotFoundHolder ()
  {
  }

  public ENotFoundHolder (lagern.LagerPackage.ENotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.LagerPackage.ENotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.LagerPackage.ENotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.LagerPackage.ENotFoundHelper.type ();
  }

}
