package lagern;


/**
* lagern/LagerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Mittwoch, 3. April 2013 16:15 Uhr MESZ
*/

abstract public class LagerHelper
{
  private static String  _id = "IDL:lagern/Lager:1.0";

  public static void insert (org.omg.CORBA.Any a, lagern.Lager that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static lagern.Lager extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (lagern.LagerHelper.id (), "Lager");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static lagern.Lager read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LagerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, lagern.Lager value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static lagern.Lager narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof lagern.Lager)
      return (lagern.Lager)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      lagern._LagerStub stub = new lagern._LagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static lagern.Lager unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof lagern.Lager)
      return (lagern.Lager)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      lagern._LagerStub stub = new lagern._LagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
