package lagern;


/**
* lagern/TFachlisteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Mittwoch, 3. April 2013 16:15 Uhr MESZ
*/

public final class TFachlisteHolder implements org.omg.CORBA.portable.Streamable
{
  public lagern.Fach value[] = null;

  public TFachlisteHolder ()
  {
  }

  public TFachlisteHolder (lagern.Fach[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.TFachlisteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.TFachlisteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.TFachlisteHelper.type ();
  }

}
