package lagern.FachPackage;


/**
* lagern/FachPackage/EInvalidCount.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Mittwoch, 3. April 2013 16:15 Uhr MESZ
*/

public final class EInvalidCount extends org.omg.CORBA.UserException
{
  public String s = null;

  public EInvalidCount ()
  {
    super(EInvalidCountHelper.id());
  } // ctor

  public EInvalidCount (String _s)
  {
    super(EInvalidCountHelper.id());
    s = _s;
  } // ctor


  public EInvalidCount (String $reason, String _s)
  {
    super(EInvalidCountHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class EInvalidCount
