package lagern.FachPackage;


/**
* lagern/FachPackage/ENotEnoughPieces.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Mittwoch, 3. April 2013 16:15 Uhr MESZ
*/

public final class ENotEnoughPieces extends org.omg.CORBA.UserException
{
  public String s = null;

  public ENotEnoughPieces ()
  {
    super(ENotEnoughPiecesHelper.id());
  } // ctor

  public ENotEnoughPieces (String _s)
  {
    super(ENotEnoughPiecesHelper.id());
    s = _s;
  } // ctor


  public ENotEnoughPieces (String $reason, String _s)
  {
    super(ENotEnoughPiecesHelper.id() + "  " + $reason);
    s = _s;
  } // ctor

} // class ENotEnoughPieces
