package lagern.FachPackage;

/**
* lagern/FachPackage/ENotEnoughPiecesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lager.idl
* Mittwoch, 3. April 2013 16:15 Uhr MESZ
*/

public final class ENotEnoughPiecesHolder implements org.omg.CORBA.portable.Streamable
{
  public lagern.FachPackage.ENotEnoughPieces value = null;

  public ENotEnoughPiecesHolder ()
  {
  }

  public ENotEnoughPiecesHolder (lagern.FachPackage.ENotEnoughPieces initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lagern.FachPackage.ENotEnoughPiecesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lagern.FachPackage.ENotEnoughPiecesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lagern.FachPackage.ENotEnoughPiecesHelper.type ();
  }

}
